#!/usr/bin/env bash

if [[ -f /data/github/shared/env.d/*smtp.sh ]]; then
  . /data/github/shared/env.d/*smtp.sh
else
  echo 'This node has no SMTP config, alerting is not going to work'
fi

# Run the backup
./bin/backup perform -t ghe -c config.rb
